# Generated by Django 5.1.3 on 2026-02-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.CharField(max_length=10),
        ),
    ]
